Hu-Fi/hufi

campaign-launcher/interface/src/abi/HumanUSD.json, campaign-launcher/interface/src/api/client/Api.ts, campaign-launcher/interface/src/api/client/data-contracts.ts, campaign-launcher/interface/src/api/manifest.ts, campaign-launcher/interface/src/constants/husd.ts, campaign-launcher/interface/src/hooks/human-protocol-sdk/escrow.ts, campaign-launcher/interface/src/hooks/human-protocol-sdk/husd.ts, campaign-launcher/interface/src/pages/create-campaign/CreateCampaign.tsx, campaign-launcher/interface/src/types/manifest.ts, campaign-launcher/server/src/modules/manifest/manifest.dto.ts, campaign-launcher/server/src/modules/manifest/manifest.service.ts
Original ticket is supposed to move the logic to the server, but we can keep the logic on frontend. Just added check logic for campaign launch.
- Added new logic to check campaign launch eligibility.
- Removed download function from manifest service.
Check if mint still works on preview deployment
Closes #28
=> check campaign launch eligibility

recording-oracle/src/common/config/web3-config.service.ts, recording-oracle/src/modules/records/records.service.ts, reputation-oracle/src/common/config/web3-config.service.ts, reputation-oracle/src/modules/payout/payout.service.ts, reputation-oracle/src/modules/storage/storage.service.ts
Update Recording oracle config.
Added getter for Recording oracle in config service
https://github.com/Hu-Fi/hufi/issues/35
=> Update recording oracle configs

recording-oracle/src/modules/records/records.service.ts, recording-oracle/src/modules/storage/storage.service.ts
Push all liquidities at once.
Add date to storage service to keep historical scores
https://github.com/Hu-Fi/hufi/issues/34
https://github.com/Hu-Fi/hufi/issues/36
=> Push all scores once and keep historical scores

campaign-launcher/interface/src/components/crypto-entity/CryptoEntity.tsx, campaign-launcher/interface/src/constants/token.ts, campaign-launcher/interface/src/hooks/human-protocol-sdk/husd.ts, campaign-launcher/interface/src/types/token.ts, recording-oracle/src/modules/campaign/campaign.repository.ts, recording-oracle/src/modules/campaign/campaign.service.ts, recording-oracle/src/modules/exchange/uniswap.service.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.controller.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts, recording-oracle/vercel.json, reputation-oracle/package.json, reputation-oracle/src/common/config/network-config.service.ts, reputation-oracle/src/common/constants/index.ts, reputation-oracle/src/common/constants/networks.ts, reputation-oracle/src/database/migrations/1718643046241-initialSetup.ts, reputation-oracle/src/modules/app/app.module.ts, reputation-oracle/src/modules/payout/payout.controller.ts, reputation-oracle/src/modules/payout/payout.module.ts, reputation-oracle/src/modules/payout/payout.service.ts, reputation-oracle/src/modules/storage/storage.service.ts, reputation-oracle/src/modules/webhook/webhook.service.ts, reputation-oracle/typeorm.config.ts, reputation-oracle/vercel.json, scripts/docker-compose.yml
Fix things up in campaign launcher/recording/reputation oracles, for e2e stable coin demo.
- Used token contract address inside campaign details for HUSD.
- Fixed uniswap subgraph query to use origin instead of sender.
- Sepolia support to the reputation oracle.
- DB migration for vercel build.
Closes #65
=> fix: recording & reputation oracle for stable coin demo

recording-oracle/vercel.json, reputation-oracle/vercel.json
We need to define vercel redirection rule to make the express routing work.
=> feat: add new vercel api functions

recording-oracle/src/common/utils/signature.ts, recording-oracle/src/modules/exchange/uniswap.service.ts, reputation-oracle/src/modules/payout/payout.service.ts
Fixed two issues with recording & reputation oracle.
- Use abs value for uniswap amount.
- Only process pending/partial escrows.
=> fix manual payout campaign fetch

reputation-oracle/src/modules/payout/payout.service.ts, reputation-oracle/src/modules/webhook/webhook.service.ts
Fixing couple issues with reputation oracle for the demo.
- Fixed escrow status check.
- Fixed bignumber math for liquidity score calculation.
=> fix reputation oracle big number math

campaign-launcher/interface/src/pages/main/Main.tsx
Display the status column on campaign launcher interface.
- Added a new column definition.
Confirm the new column is displayed on campaign launcher UI.
Closes #71
=> add status column to the campaign launcher

recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts
Run cron job every day at midnight to calculate liquidity score of active campaigns.
- Changed cron interval.
- Skipped empty liquidity recorded for the day.
Closes #73
=> feat: [Recording Oracle] Daily cron job to calculate liquidity score

recording-oracle/vercel.json, reputation-oracle/vercel.json
Recording/Reputation oracle API gives CORS error.
- Updated vercel.json for both recording/reputation oracle to define cors for every route.
=> update vercel cors config

campaign-launcher/interface/yarn.lock
=> update yarn lock

campaign-launcher/interface/src/types/pair.ts
=> fix build issue

recording-oracle/src/modules/exchange/ccxt.service.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts
Recording oracle is fetching any open order, but it should consider the since timestamp, because we are doing daily payouts.
- Added `since` param to fetchOpenOrder function.
Closes #101
=> fix open order fetch recording oracle

recording-oracle/src/modules/exchange/ccxt.service.ts
=> feat: ccxt pro support

campaign-launcher/interface/src/components/crypto-entity/CryptoEntity.tsx, campaign-launcher/interface/src/pages/create-campaign/CreateCampaign.tsx, campaign-launcher/interface/src/pages/main/Main.tsx, campaign-launcher/server/src/modules/campaign/campaign.service.ts, reputation-oracle/src/modules/payout/payout.service.ts
=> fix campaign launcher dashboard and payout service

campaign-launcher/interface/src/hooks/recording-oracle/user.ts, campaign-launcher/interface/src/pages/campaign-detail/CampaignDetail.tsx, recording-oracle/src/database/entities/campaign.entity.ts, recording-oracle/src/database/migrations/1723689218832-updateCampaignDateFieldType.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts, recording-oracle/src/modules/user/user.controller.ts, recording-oracle/src/modules/user/user.service.ts, reputation-oracle/src/modules/payout/payout.service.ts
- Recording Oracle: Changed the column type from date to datetime for campaign start/end date
- Reputation Oracle: Removed campaign end date check, and rely on escrow status
- Campaign Launcher: Remove API key association dialog when user already has the key
=> fix recording oracle with datetime field type

.github/workflows/cd-campaign-launcher-server.yaml, .github/workflows/cd-campaign-launcher-ui.yaml, .github/workflows/cd-recording-oracle.yaml, .github/workflows/cd-reputation-oracle.yaml, campaign-launcher/interface/src/pages/main/Main.tsx, recording-oracle/src/modules/records/records.service.ts, recording-oracle/src/modules/web3/web3.service.ts, reputation-oracle/src/modules/payout/payout.service.ts, reputation-oracle/src/modules/web3/web3.service.ts, reputation-oracle/src/modules/webhook/webhook.service.ts
=> use increased gas

campaign-launcher/interface/src/App.tsx, campaign-launcher/interface/src/components/connect-wallet/ConnectWallet.tsx, campaign-launcher/interface/src/hooks/human-protocol-sdk/escrow.ts, campaign-launcher/interface/src/hooks/recording-oracle/auth.tsx, campaign-launcher/interface/src/hooks/recording-oracle/campaign.ts, campaign-launcher/interface/src/hooks/recording-oracle/user.ts, campaign-launcher/interface/src/pages/campaign-detail/CampaignDetail.tsx, recording-oracle/src/modules/user/user.controller.ts, recording-oracle/src/modules/user/user.service.ts
- Fix User Campaign Registration status check.
- Fix Campaign Launch Fund part.
=> fix: campaign launcher ui

campaign-launcher/interface/src/hooks/human-protocol-sdk/escrow.ts, recording-oracle/src/modules/mr-market/mr-market.controller.ts, recording-oracle/src/modules/mr-market/mr-market.service.ts
=> feat: add mr.market campaign join status endpoint

campaign-launcher/interface/src/pages/create-campaign/CreateCampaign.tsx
=> use 6 decimal for usdt

campaign-launcher/interface/src/pages/create-campaign/CreateCampaign.tsx, campaign-launcher/interface/src/utils/token.ts, reputation-oracle/src/modules/webhook/webhook.service.ts
=> Release #241211

campaign-launcher/interface/src/hooks/human-protocol-sdk/escrow.ts, campaign-launcher/interface/src/pages/create-campaign/CreateCampaign.tsx, campaign-launcher/interface/src/utils/token.ts
=> fix: token decimal

recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts, recording-oracle/src/modules/mr-market/mr-market.service.ts, reputation-oracle/src/modules/webhook/webhook.service.ts
=> fix: recording oracle exchange api key

recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts
=> fix: recording oracle liquidity score calculation for the user

recording-oracle/src/modules/exchange/ccxt.service.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts, reputation-oracle/src/modules/payout/payout.service.ts
=> fix: use cost field to calculate liquidity score

recording-oracle/src/modules/exchange/ccxt.service.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts, reputation-oracle/src/modules/payout/payout.service.ts
=> Release #250113

recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts, reputation-oracle/src/modules/payout/payout.service.ts
=> fix: round the liquidity score

recording-oracle/src/modules/exchange/ccxt.service.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts, reputation-oracle/src/modules/payout/payout.service.ts
=> Release #250114

campaign-launcher/interface/package.json, campaign-launcher/interface/yarn.lock, campaign-launcher/server/package.json, campaign-launcher/server/yarn.lock, recording-oracle/package.json, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts, recording-oracle/yarn.lock, reputation-oracle/package.json, reputation-oracle/src/modules/webhook/webhook.service.ts, reputation-oracle/yarn.lock
=> feat: update sdk

campaign-launcher/interface/package.json, campaign-launcher/interface/yarn.lock, campaign-launcher/server/package.json, campaign-launcher/server/yarn.lock, recording-oracle/package.json, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts, recording-oracle/yarn.lock, reputation-oracle/package.json, reputation-oracle/src/modules/payout/payout.service.ts, reputation-oracle/src/modules/webhook/webhook.service.ts, reputation-oracle/yarn.lock
=> Release #250117

campaign-launcher/server/src/modules/campaign/campaign.controller.ts
=> fix: remove create-campaign endpoint

campaign-launcher/interface/src/components/network-switch/NetworkSwitcher.tsx, campaign-launcher/interface/src/layout/Header.tsx
=> fix: build issue

campaign-launcher/server/src/modules/campaign/campaign.controller.ts, campaign-launcher/server/src/modules/campaign/campaign.service.ts, campaign-launcher/server/src/modules/web3/web3.service.ts
=> Add Campaign stats

reputation-oracle/src/modules/web3-transaction/web3-transaction.service.ts, reputation-oracle/src/modules/web3/web3.service.ts
Fix Problems with reputation oracle.
=> Fix reputation oracle failure

recording-oracle/src/database/entities/liquidity-score.entity.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts, recording-oracle/src/modules/records/records.service.ts, recording-oracle/src/modules/web3-transaction/web3-transaction.service.ts
Fix Liquidity score failure 
Fix Web3 transaction failure
add Window start and end to liquidity score calculation
=> Fix liquidity score and tx failure

recording-oracle/src/database/migrations/1745497565934-AddWindowToLiquidityScores.ts
=> Add migration file

reputation-oracle/src/modules/webhook/webhook.service.ts
Filter out zero payments from bulk payout.
=> filter out zero payments from bulkpayout

reputation-oracle/src/modules/payout/payout.service.ts
Fix bigint serializartion error by converting it to string to be save in db
ERROR [PayoutService] Error finalizing campaign:
ERROR [PayoutService] TypeError: Do not know how to serialize a BigInt
=> fix bigint serialization failure

recording-oracle/src/modules/liquidity-score/liquidity-score.controller.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts
Added Total liquidity score endpoint to be used as a metric.
=> Add total Liquidity score endpoint

reputation-oracle/src/modules/webhook/webhook.service.ts
Add the daily cap to the campaign payouts.
=> Apply daily pay cap

campaign-launcher/interface/package.json, campaign-launcher/interface/yarn.lock, campaign-launcher/server/package.json, campaign-launcher/server/yarn.lock, recording-oracle/package.json, recording-oracle/yarn.lock, reputation-oracle/package.json, reputation-oracle/yarn.lock
Upgrade @human-protocol/sdk version
=> Upgrade @human-protocol/sdk version

recording-oracle/src/database/base.entity.ts, recording-oracle/src/database/migrations/1746709598183-addDefaultDate.ts, recording-oracle/src/modules/web3-transaction/web3-transaction.service.ts, reputation-oracle/src/modules/webhook/webhook.service.ts
- Fix for dates deault value
- Remove web3 transactions from reputation oracle
=> Fixes from testing on staging

recording-oracle/src/common/constants/errors.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.controller.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.repository.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts
Fix the way of handling start and end dates of liquidity calculations to avoid double registering the score for the same period of time
=> Fix score windows

recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts
=> Refactor while loop condition

reputation-oracle/src/database/database.module.ts, reputation-oracle/src/database/pg-lock.service.ts, reputation-oracle/src/modules/payout/payout.module.ts, reputation-oracle/src/modules/payout/payout.service.ts, reputation-oracle/src/modules/web3-transaction/web3-transaction.module.ts, reputation-oracle/src/modules/web3-transaction/web3-transaction.service.ts, reputation-oracle/src/modules/webhook/webhook.module.ts, reputation-oracle/src/modules/webhook/webhook.service.ts
Add cron locks to avoid simultaneous executions
=> Add cron locks

recording-oracle/src/modules/campaign/campaign.controller.ts, recording-oracle/src/modules/campaign/campaign.service.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.model.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts
- Changed the getActiveCampaigns to check for the live campaigns on chain
- Added endpoint to check the active campaigns and their users. 
- Improve liquidity score calculation to avoid errors
- Push and store liquidity score outside the user loop in the calculation.
=> minor fixes in recording oracle

campaign-launcher/server/src/common/constants/networks.ts, campaign-launcher/server/src/modules/campaign/campaign.dto.ts, campaign-launcher/server/src/modules/campaign/campaign.service.ts, campaign-launcher/server/src/modules/web3/web3.service.ts, recording-oracle/src/common/constants/networks.ts, recording-oracle/src/modules/user/user.controller.ts, recording-oracle/src/modules/user/user.dto.ts, recording-oracle/src/modules/user/user.service.ts, recording-oracle/src/modules/web3/web3.service.ts
N/A
Add token symbol retrieval and refactor token decimals handling
Deployed locally
None
None
=>  [Campaign Launcher] Token symbol

campaign-launcher/server/src/modules/campaign/campaign.dto.ts, campaign-launcher/server/src/modules/campaign/campaign.service.ts
Revert #241
Remove last24hAmountPaid as it's no longer needed
None
None
None
=> [Campaign Launcher] Remove last24hAmountPaid property

recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/utils/manifest.spec.ts, recording-oracle/src/utils/manifest.ts
#254 
Added manifest hash validation upon creating a campaign.
N/A
N/A
=> [Recording Oracle] Added manifest hash validation

recording-oracle/src/modules/campaign/campaign.service.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts
Closes #239 
Adjust date handling to use UTC for consistency
NA
=> Adjust date handling to use UTC for consistency

campaign-launcher/interfaceV2/package.json, campaign-launcher/interfaceV2/src/api/client.ts, campaign-launcher/interfaceV2/yarn.lock, recording-oracle/package.json, recording-oracle/yarn.lock, reputation-oracle/package.json, reputation-oracle/yarn.lock
#277 
Bumped `@human-protocol/sdk` version to 4.1.4 due to the subgraph issues with older versions
N/A
N/A
=> [V2] feat: bump `@human-protocol/sdk` to 4.1.4

recording-oracle/package.json, recording-oracle/yarn.lock
Freestyle
Freeze `ethers` for recording oracle at ~6.13.5 
N/A
N/A
=> [V2] Freeze `ethers` for recording oracle

recording-oracle/src/modules/campaign/campaign.repository.ts, recording-oracle/src/modules/liquidity-score/liquidity-score.service.ts, recording-oracle/src/modules/user/user.repository.ts
NA
- Prevent future score calculations for campaigns in LiquidityScoreService
- Fix finds with case sensitive addresses
Debug
NA
NA
=> Recording oracle fixes

recording-oracle/src/common/utils/http.ts, recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/campaigns/manifest.utils.spec.ts, recording-oracle/src/modules/campaigns/manifest.utils.ts, reputation-oracle/src/common/utils/http.ts, reputation-oracle/src/modules/payouts/payouts.service.ts, reputation-oracle/src/modules/payouts/payouts.utils.ts
#284 
Added support for the manifest embedded in escrow in Recording/Reputation oracles.
N/A
N/A
=> [V2] Support for the manifest embedded in escrow

recording-oracle/src/modules/campaigns/campaigns.controller.ts, recording-oracle/src/modules/campaigns/campaigns.dto.ts, recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/web3/web3.service.spec.ts, recording-oracle/src/modules/web3/web3.service.ts
Freestyle
Added the endpoint to check if user joined to campaign since such info needed for UI in order to properly render "join" button status
Just merge
No
=> [v2] feat: add endpoint to check if user has joined the campaign

campaign-launcher/server/package.json, campaign-launcher/server/src/modules/campaigns/campaigns.service.ts, campaign-launcher/server/yarn.lock, recording-oracle/package.json, recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/campaigns/manifest.utils.spec.ts, recording-oracle/yarn.lock, reputation-oracle/package.json, reputation-oracle/src/modules/payouts/payouts.service.ts, reputation-oracle/src/modules/payouts/types.ts, reputation-oracle/yarn.lock
#308 
Bumping `@human-protocol/sdk` version to 4.2.0 which allows us to operate with manifest as a JSON.
N/A
N/A
=> [V2] Bump `@human-protocol/sdk` to 4.2.0

campaign-launcher/server/package.json, campaign-launcher/server/src/modules/campaigns/campaigns.controller.ts, campaign-launcher/server/src/modules/campaigns/campaigns.dto.ts, campaign-launcher/server/src/modules/campaigns/campaigns.service.ts, campaign-launcher/server/src/modules/campaigns/types.ts, campaign-launcher/server/yarn.lock
Part of #282 
Added info about campaign oracle fees + caching headers for campaign details since we don't expect them update too often.
Just merge
No
=> [v2] feat: add campaign oracle fees info

reputation-oracle/src/modules/payouts/payouts.service.ts
#309 
In a current implementation we're not supporting proper payouts for the campaigns running for more than a day.
This temp hack is aimed at fixing this issue till escrow contract upgrades (payoutId related) are deployed.
In a nutshell: skipping campaign timeframes based on BulkTransferV2 events count.
Tested the script for fetching BulkTransferV2 events count separately.
N/A
During e2e testing on staging need to launch relatively long-running campaigns (more than a day) and monitor the behaviour.
=> [V2][Reputation Oracle] Skipping timeframes based on the BulkTransferV2 events count

recording-oracle/src/modules/admin/admin.error-filter.ts
Follow up to https://github.com/Hu-Fi/hufi/pull/317
Missed file while adding changes in git. Added it here.
N/A
Just merge
No
=> [v2] fix: add missing admin filter file

campaign-launcher/interfaceV2/src/components/ApiKeysTable/index.tsx, campaign-launcher/interfaceV2/src/components/CampaignsTable/index.tsx, campaign-launcher/interfaceV2/src/components/modals/AddApiKeyModal/index.tsx, campaign-launcher/interfaceV2/src/components/modals/CreateCampaignModal/index.tsx, campaign-launcher/interfaceV2/src/hooks/recording-oracle/campaign.ts, campaign-launcher/interfaceV2/src/hooks/useCreateEscrow.ts, campaign-launcher/interfaceV2/src/providers/WagmiProvider.tsx, campaign-launcher/interfaceV2/src/utils/index.ts
Freestyle
This PR improves UI of a various components:
- adds loading state to the trading pair select;
- invalidates `check-is-joined-campaign` query after user joins a campaign;
- reworks `useCreateEscrow` hook such, that it looks like react query hook and returns similar data;
- makes tables responsive
- removes weird empty cells in the tables
- changes wagmi config, so it returns different config objects depending on NODE_ENV
locally
regular
=> [Launcher UI V2] - UI improvements

campaign-launcher/interfaceV2/src/components/SignInButton/index.tsx, campaign-launcher/interfaceV2/src/hooks/useRetrieveSigner.ts, campaign-launcher/interfaceV2/src/providers/ActiveAccountProvider.tsx, campaign-launcher/interfaceV2/src/providers/Web3AuthProvider.tsx
Not ticketed
This PR aims to fix all the encountered issues that have to do with having multiple connected accounts via metamask
locally
regular plan
not found
=> [Launcher UI V2] Fix the Multiple accounts issues

campaign-launcher/server/src/common/filters/exception.ts, recording-oracle/src/common/filters/exception.ts, reputation-oracle/src/modules/payouts/payouts.service.ts
=> [v2] feat: improve logs & error responses

.github/workflows/run-reputation-oracle.yaml, campaign-launcher/server/.env.example, campaign-launcher/server/src/common/constants/chains.ts, campaign-launcher/server/src/config/env-schema.ts, campaign-launcher/server/src/config/web3-config.service.ts, recording-oracle/.env.example, recording-oracle/src/common/constants/chains.ts, recording-oracle/src/config/env-schema.ts, recording-oracle/src/config/web3-config.service.ts, reputation-oracle/.env.example, reputation-oracle/src/common/constants/chains.ts, reputation-oracle/src/config/env-schema.ts, reputation-oracle/src/config/web3-config.service.ts
=> Release 2025-08-26 [2]

campaign-launcher/client/src/api/launcherApiClient.ts, campaign-launcher/client/src/hooks/useCreateEscrow.ts, campaign-launcher/client/src/types/index.ts, campaign-launcher/server/src/modules/web3/web3.controller.ts, campaign-launcher/server/src/modules/web3/web3.dto.ts, campaign-launcher/server/src/modules/web3/web3.module.ts
=> Release 2025-08-26 [3]

recording-oracle/src/common/types/request.ts, recording-oracle/src/modules/admin/admin.service.ts, recording-oracle/src/modules/auth/jwt-http-strategy.ts, recording-oracle/src/modules/campaigns/campaigns.controller.ts, recording-oracle/src/modules/campaigns/campaigns.dto.ts, recording-oracle/src/modules/campaigns/campaigns.errors.ts, recording-oracle/src/modules/campaigns/campaigns.module.ts, recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/campaigns/types.ts
#367 
1. Added `evmAddress` to `RequestWithUser` to avoid unnecessary imports and DB calls.
2. Added an LRU cache with a 10-minute TTL for storing campaign statistics.
- Note: timeframe definition:
A timeframe starts at `campaign.startDate + n * 24h`, where `n = floor((now - campaign.startDate) / 24h)`. e.g.
campaign start: 2025-09-02T07:56:12.728Z
current time: 2025-09-03T15:56:12.728Z
current timeframe start: 2025-09-03T07:56:12.728Z
- Key: `chainId-address-timeframeStart`. `timeframeStart` is included to prevent edge cases where a new timeframe has started but cached data from the previous timeframe still exists.
- All participant results for a campaign/timeframe are stored in this cache.
3. Changed `/campaigns/{chain_id}-{campaign_address}/my-progress` endpoint:
- New response schema: …
=> [Recording Oracle] Track user's and general statistics for a current active campaign window

campaign-launcher/client/package.json, campaign-launcher/client/src/hooks/useCreateEscrow.ts, campaign-launcher/client/yarn.lock
Freestyle
Bumps sdk's version to latest along with `@human-protocol/core` and `ethers`
locally
most likely need to wait until the next stable version of sdk
not found
=> [Launcher UI] Update SDK

campaign-launcher/client/package.json, campaign-launcher/client/src/api/recordingApiClient.ts, campaign-launcher/client/src/components/CampaignResultsWidget/index.tsx, campaign-launcher/client/src/components/CampaignStats/index.tsx, campaign-launcher/client/src/components/CampaignsTable/index.tsx, campaign-launcher/client/src/components/CryptoEntity/index.tsx, campaign-launcher/client/src/components/CryptoPairEntity/index.tsx, campaign-launcher/client/src/components/DashboardStats/index.tsx, campaign-launcher/client/src/components/TotalVolume/index.tsx, campaign-launcher/client/src/components/modals/CreateCampaignModal/index.tsx, campaign-launcher/client/src/hooks/recording-oracle/campaign.ts, campaign-launcher/client/src/hooks/recording-oracle/exchangeApiKeys.ts, campaign-launcher/client/src/hooks/recording-oracle/user.ts, campaign-launcher/client/src/pages/Campaign/index.tsx, campaign-launcher/client/src/providers/ActiveAccountProvider.tsx, campaign-launcher/client/src/providers/QueryClientProvider.tsx, campaign-launcher/client/src/theme.ts, campaign-launcher/client/src/types/index.ts, campaign-launcher/client/src/utils/index.ts, campaign-launcher/client/yarn.lock
=> Release 2025-09-25

campaign-launcher/server/src/modules/campaigns/campaigns.dto.ts, campaign-launcher/server/src/modules/campaigns/campaigns.service.ts, campaign-launcher/server/src/modules/campaigns/manifest.utils.ts, campaign-launcher/server/src/modules/campaigns/types.ts, campaign-launcher/server/src/modules/exchanges/exchanges.controller.ts, campaign-launcher/server/src/modules/exchanges/exchanges.service.ts, campaign-launcher/server/types/ccxt.d.ts
To close #396 
1. Added new endpoint `GET /:exchange_name/currencies` for fetching supported currencies.
2. Changed `CampaignData` schema:
- Added `type` (`VOLUME` | `LIQUIDITY`)
- Added `details` which will contain either `daily_volume_target` or `daily_balance_target` based on a campaign type
- `trading_pair` renamed to `symbol`
3. Added support for a new campaign type - `LIQUIDITY`
4. `MARKET_MAKING` is renamed to `VOLUME`
5. Manifest changes:
- `trading_pair` renamed to `symbol` in a manifest.
- For the `LIQUIDITY` type added `daily_balance_target` field. (`daily_volume_target` is available in `VOLUME` campaigns)
Deployed locally and tested
N/A
=> [Campaign Launcher server] Added support of `LIQUIDITY` campaign type

campaign-launcher/client/src/components/CampaignTypeLabel/index.tsx
Freestyle
Just fixing a color
locally
regular
not found
=> [Launcher UI] Fix background color of campaign type label

campaign-launcher/client/src/components/modals/CreateCampaignModal/index.tsx, campaign-launcher/client/src/hooks/useCreateEscrow.ts
Freestyle
Cherry-picking #388 to `develop`
locally
regular
not found
=> [Launcher UI] feat: handle errors while creating a campaign (cherry-pick)
