campaign-launcher/interface/src/hooks/human-protocol-sdk/escrow.ts
There are some manifest URL that has `http` instead of `https` for the google cloud storage objects. The server was not configured to use SSL, so this insecure URL is generated. It's already on-chain data, so need to replace it with https from front-end.
- Added a string replacement from `http://storage.googleapis.com` to `https://storage.googleapis.com`
Check if dashboard main page is displayed.
=> fix manifest https google cloud storage

recording-oracle/.env.example, recording-oracle/src/common/config/env-schema.ts, recording-oracle/src/common/config/server-config.service.ts, recording-oracle/src/common/guards/api-key.guard.ts, recording-oracle/src/modules/records/records.controller.ts, recording-oracle/src/modules/user/user.controller.ts, recording-oracle/src/modules/user/user.dto.ts
- Added `x-api-key` header for authentication.
- Updated swagger doc.
From the security perspective, we need to protect the API endpoints, since it'll be used from other services like campaign launcher server / Mr.market.
Try API endpoints on Swagger with/without api key.
Closes #48
=> [Recording Oracle] feat: add API key protection

recording-oracle/src/app.module.ts, recording-oracle/src/common/constants/errors.ts, recording-oracle/src/modules/mr-market/mr-market.controller.ts, recording-oracle/src/modules/mr-market/mr-market.dto.ts, recording-oracle/src/modules/mr-market/mr-market.module.ts, recording-oracle/src/modules/mr-market/mr-market.service.ts
Added `/mr-market/campaign` endpoint that is protected by API key.
This allows Mr.Market to join the campaign directly without auth.
Closes #122
=> feat: add recording oracle endpoint for Mr.Market

recording-oracle/eslint.config.mjs, recording-oracle/package.json, recording-oracle/src/database/database.module.ts, recording-oracle/src/database/migrations/1748865118682-initial-setup.ts, recording-oracle/src/logger/index.ts, recording-oracle/src/modules/auth/token.entity.ts, recording-oracle/src/modules/health/health.controller.spec.ts, recording-oracle/src/modules/health/health.controller.ts, recording-oracle/src/modules/users/user.entity.ts, recording-oracle/src/modules/users/users.service.ts, recording-oracle/src/utils/web3.ts, recording-oracle/tsconfig.json, recording-oracle/yarn.lock
Having an imports alias improves imports readability and improves DX in terms of refactoring (e.g. because it's easier to search by `@/config` rather than all possible `../..` variations
- added alias for `src` in tsconfig
- installed and configured necessary plugins so all dev scripts/tools work correctly
- fixed `yarn start:prod` command
- replaced all relative paths with alias
Freestyle
=> [Recording Oracle] feat: add src folder alias

.github/workflows/ci-test.yaml, package.json, recording-oracle/package.json, recording-oracle/src/common/types/index.ts, recording-oracle/src/common/types/manifest.ts, recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/campaigns/fixtures/index.ts, recording-oracle/src/modules/campaigns/index.ts, recording-oracle/src/modules/campaigns/types.ts, recording-oracle/src/modules/exchange-api-keys/fixtures/index.ts, recording-oracle/src/modules/exchange/ccxt-exchange-client.spec.ts, recording-oracle/src/modules/exchange/fixtures/index.ts, recording-oracle/src/modules/web3/fixtures/index.ts, recording-oracle/src/modules/web3/web3.service.spec.ts, recording-oracle/src/utils/manifest.spec.ts, recording-oracle/src/utils/manifest.ts, recording-oracle/test/fixtures/manifest.ts, recording-oracle/yarn.lock, scripts/Makefile
Part of #236 
- added unit tests for campaigns service and web3 service as well
- moved `CampaignManifest` type to `common` folder in order to avoid potential circular dependency in the future + it's not part of the campaign module itself, it's something general atm because we also have manifest utils
- enabled unit tests in CI
Just merge
No
=> [Recording Oracle] test: campaigns service

recording-oracle/package.json, recording-oracle/src/app.module.ts, recording-oracle/src/common/interceptors/transform.ts, recording-oracle/src/database/database.module.ts, recording-oracle/src/database/migrations/1752851913318-volume-stats.ts, recording-oracle/src/main.ts, recording-oracle/src/modules/campaigns/campaigns.module.ts, recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/campaigns/index.ts, recording-oracle/src/modules/campaigns/volume-stat.entity.ts, recording-oracle/src/modules/campaigns/volume-stats.repository.ts, recording-oracle/src/modules/statistics/index.ts, recording-oracle/src/modules/statistics/statistics.controller.ts, recording-oracle/src/modules/statistics/statistics.dto.ts, recording-oracle/src/modules/statistics/statistics.module.ts, recording-oracle/src/modules/statistics/statistics.service.ts, recording-oracle/yarn.lock
Closes #271
Unfortunately we can't get daily stats because we get generated volume for different periods in different campaigns, so recording actual stats would be an overhead for now.
Taking into account that this endpoint is public and that volume data is not updated frequently, apply caching on controller level and also avoid multiple identical queries running in parallel.
Just merge PR.
For local dev - `yarn install & yarn migration: run` after merge.
No.
=> [Recording Oracle] feat: total volume stats

campaign-launcher/interfaceV2/src/components/CampaignInfo/index.tsx, campaign-launcher/interfaceV2/src/components/CampaignsTable/index.tsx, campaign-launcher/interfaceV2/src/components/NetworkSwitcher/index.tsx, campaign-launcher/interfaceV2/src/utils/index.ts
Not ticketed
We want to indicate a campaign's network
locally on both pages
regular plan
no risks
=> Display Campaign's Network Icon

campaign-launcher/server/.env.example, campaign-launcher/server/src/common/constants/index.ts, campaign-launcher/server/src/common/validators/web3.ts, campaign-launcher/server/src/config/env-schema.ts, campaign-launcher/server/src/config/web3-config.service.ts, campaign-launcher/server/src/modules/campaigns/campaigns.dto.ts, campaign-launcher/server/src/modules/campaigns/campaigns.service.ts, campaign-launcher/server/src/modules/campaigns/types.ts, recording-oracle/.env.example, recording-oracle/package.json, recording-oracle/src/common/constants/index.ts, recording-oracle/src/common/validators/web3.ts, recording-oracle/src/config/env-schema.ts, recording-oracle/src/config/web3-config.service.ts, recording-oracle/src/database/migrations/1753973381832-initial-migration.ts, recording-oracle/src/database/migrations/1754303207946-initial-migration.ts, recording-oracle/src/modules/campaigns/campaigns.controller.ts, recording-oracle/src/modules/campaigns/campaigns.dto.ts, recording-oracle/src/modules/campaigns/campaigns.repository.ts, recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/campaigns/fixtures/campaign.ts, recording-oracle/src/modules/campaigns/types.ts, recording-oracle/src/modules/campaigns/user-campaigns.repository.ts, recording-oracle/src/modules/campaigns/volume-stat.entity.ts, recording-oracle/src/modules/statistics/statistics.dto.ts, recording-oracle/src/modules/statistics/statistics.service.ts, recording-oracle/src/modules/web3/web3.service.spec.ts, recording-oracle/src/modules/web3/web3.service.ts, recording-oracle/yarn.lock
Part of #282 
- some exchanges (e.g. `alpaca`) do not allow getting trading pairs w/o api key, so we decided to go with a specific list of exchanges for now instead of supporting all from `ccxt`
- added statuses mapping for public API, so campaigns always have one of three statuses: `active`, `cancelled`, `completed` and UI can add extra details/clarifications based on supplied campaign data;
- in order to support the above - we added new campaign status to recording oracle and cron job to track escrow completion; also original status values returns just for convenience
- campaign might have different `quote` symbol, hence volume is calculate in `quote` currency; taking into account that stats must be provided in unified format (USD), we have to convert such value, so
- we will use …
=> [v2] feat: campaign statuses mapping; change supported exchanges

recording-oracle/.env.example, recording-oracle/src/app.module.ts, recording-oracle/src/common/utils/crypto.ts, recording-oracle/src/config/auth-config.service.ts, recording-oracle/src/modules/admin/admin.controller.ts, recording-oracle/src/modules/admin/admin.dto.ts, recording-oracle/src/modules/admin/admin.module.ts, recording-oracle/src/modules/admin/admin.service.ts, recording-oracle/src/modules/admin/api-key.guard.ts, recording-oracle/src/modules/admin/index.ts, recording-oracle/src/modules/campaigns/campaigns.error-filter.ts, recording-oracle/src/modules/campaigns/campaigns.module.ts, recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/campaigns/fixtures/campaign.ts, recording-oracle/src/modules/campaigns/index.ts
Freestyle
- added normalization to campaign addresses in order to properly handle search operations for `join` and `check-is-joined`
- added `admin` endpoint behind API key auth in order to enable convenient debug checks
Merge. Add API key where needed
No
=> [v2] feat: normalize campaign address and add admin endpoints

recording-oracle/src/modules/campaigns/campaigns.controller.ts, recording-oracle/src/modules/campaigns/campaigns.dto.ts, recording-oracle/src/modules/campaigns/campaigns.error-filter.ts, recording-oracle/src/modules/campaigns/campaigns.errors.ts, recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/campaigns/progress-checking/progress-checker.spec.ts
N/A
We want to provide an ability to campaign participants to see if they have some results for a campaign they joined to. In order to do that we are going to check their progress for the whole campaign period returning totals to the client.
Just merge
No
=> [v2] feat: endpoint to return user progress for campaign

campaign-launcher/server/src/common/constants/index.ts, recording-oracle/src/common/constants/index.ts, recording-oracle/src/modules/campaigns/campaigns.repository.ts, recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/campaigns/fixtures/campaign.ts, recording-oracle/src/modules/web3/fixtures/index.ts, recording-oracle/src/modules/web3/web3.service.spec.ts, recording-oracle/src/modules/web3/web3.service.ts, reputation-oracle/src/modules/payouts/payouts.service.ts
N/A
- changed DB query and code logic to allow intermediate results recording if less than a day passed from previous calculation, but campaign has already ended, so we don't have to wait e.g. for another 23h to get results just for 1h
- added payout period to RepO log for better observability
- some exchanges require passphrase w/ API key; we decided to remove them for now
Just merge
No
=> [v2] feat: improve RecO processing

campaign-launcher/interfaceV2/src/components/CampaignStats/index.tsx, campaign-launcher/interfaceV2/src/components/CampaignsTable/index.tsx, campaign-launcher/interfaceV2/src/components/DailyAmountPaidChart/index.tsx, campaign-launcher/interfaceV2/src/components/FormattedNumber/index.tsx, campaign-launcher/interfaceV2/src/components/InfoTooltipInner/index.tsx, campaign-launcher/interfaceV2/src/components/ModalState/Error.tsx, campaign-launcher/interfaceV2/src/components/modals/AddApiKeyModal/index.tsx, campaign-launcher/interfaceV2/src/components/modals/EditApiKeyModal/index.tsx, campaign-launcher/interfaceV2/src/constants/index.ts, campaign-launcher/interfaceV2/src/types/index.ts, campaign-launcher/interfaceV2/src/utils/index.ts
Not ticketed
This PR adds daily volume target information in the campaigns table and on the campaign details page;
Also in this PR i've changed some elements such that they became more responsive and handled 500 error, when we need to display error message
locally
regular
not found
=> [Launcher UI V2] Add Daily Volume Target

recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/campaigns/progress-checking/market-making.spec.ts, recording-oracle/src/modules/campaigns/progress-checking/market-making.ts, recording-oracle/src/modules/campaigns/progress-checking/progress-checker.spec.ts, recording-oracle/src/modules/campaigns/progress-checking/progress-checker.ts
N/A
- we revisited our score & volume calculation strategies and decided to count `sell` trades into total volume as well, so even if e.g. there is only participant doing maker sells they can solely reach daily volume target and be rewarded
- also count score for "taker sells" because eventually it does market making
Just merge
No
=> [v2] feat: count sell trades volume

campaign-launcher/client/src/api/launcherApiClient.ts, campaign-launcher/client/src/hooks/useCreateEscrow.ts, campaign-launcher/client/src/types/index.ts, campaign-launcher/server/src/modules/web3/web3.controller.ts, campaign-launcher/server/src/modules/web3/web3.dto.ts, campaign-launcher/server/src/modules/web3/web3.module.ts
N/A
Sometimes subgraph lags when use public version. In order to properly retrieve oracle fees we will use launcher backend now, but later will replace to direct RPC calls when SDK is updated (https://github.com/humanprotocol/human-protocol/issues/3523)
Just merge
No
=> [Campaign Launcher] feat: fetch oracle fees from cl be

campaign-launcher/client/src/components/CampaignStats/index.tsx, campaign-launcher/client/src/components/DailyAmountPaidChart/index.tsx
Freestyle
This PR fixes the bug with wrong visualization of the daily paid amounts data on the chart, taking token decimals into account
locally
regular
=> [Launcher UI] Fix Chart data

campaign-launcher/client/src/components/CampaignAddress/index.tsx, campaign-launcher/client/src/components/CampaignInfo/index.tsx, campaign-launcher/client/src/components/Campaigns/index.tsx, campaign-launcher/client/src/components/CampaignsTable/index.tsx, campaign-launcher/client/src/components/CustomTooltip/index.tsx, campaign-launcher/client/src/components/Header/index.tsx, campaign-launcher/client/src/components/JoinCampaign/index.tsx, campaign-launcher/client/src/components/PageTitle/index.tsx, campaign-launcher/client/src/components/modals/BaseModal/index.tsx, campaign-launcher/client/src/components/modals/CreateCampaignModal/index.tsx, campaign-launcher/client/src/pages/Campaign/index.tsx
Freestyle
This PR adds a full campaign address and the copy-to-clipboard functionality, which results in slight redesign of CampaignInfo component;
Also it introduces a custom tooltip component and a responsive fixes;
In the end, it shows only active campaigns by default
locally
regular
not found
=> [Launcher UI] Rework campaign details 

reputation-oracle/src/modules/payouts/payouts.service.ts
N/A
New contracts on testnet emit `bulkTransferV3` events, so in order to properly count executed payouts we need to search logs for this event, at the same time providing backward compatibility for v2 for further release.
> [!NOTE]
> I got this situation with my local testnet setup and calls of `bulkPayout` method were failing because of the same `payoutId` passed. With this fix - worked as expected and campaign completed 
As part of parent branch. Nothing special in this PR.
Remove lines with v2 when all old contracts completed after release.
N/A
=> [Reputation Oracle] fix: bulk transfer logs count

campaign-launcher/client/src/components/CampaignResultsWidget/index.tsx, campaign-launcher/client/src/components/CampaignStats/index.tsx, campaign-launcher/client/src/components/CampaignsTable/index.tsx, campaign-launcher/client/src/components/CryptoEntity/index.tsx, campaign-launcher/client/src/components/CryptoPairEntity/index.tsx, campaign-launcher/client/src/components/modals/CreateCampaignModal/index.tsx, campaign-launcher/client/src/types/index.ts, campaign-launcher/client/src/utils/index.ts
Closes #395
This PR changes the logic of the widget: final result should be displayed only if the campaign is already not active and has a final results url; otherwise it's intermediate or N/A (if no results have yet been recorded)
Also, this PR tweaks a displaying of daily volume token (usdt -> usdt0)
locally
regular
not found
=> [Launcher UI] Fix Campaign Results

recording-oracle/src/database/migrations/1758725472133-abstract-campaign-type.ts, recording-oracle/src/logger/index.ts, recording-oracle/src/modules/campaigns/campaign.entity.ts, recording-oracle/src/modules/campaigns/campaigns.controller.ts, recording-oracle/src/modules/campaigns/campaigns.dto.ts, recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/campaigns/constants.ts, recording-oracle/src/modules/campaigns/fixtures/campaign.ts, recording-oracle/src/modules/campaigns/fixtures/manifest.ts, recording-oracle/src/modules/campaigns/manifest.utils.spec.ts, recording-oracle/src/modules/campaigns/manifest.utils.ts, recording-oracle/src/modules/campaigns/progress-checking/index.ts, recording-oracle/src/modules/campaigns/progress-checking/progress-checker.spec.ts, recording-oracle/src/modules/campaigns/progress-checking/progress-checker.ts, recording-oracle/src/modules/campaigns/progress-checking/types.ts, recording-oracle/src/modules/campaigns/type-guards.ts, recording-oracle/src/modules/campaigns/types.ts
N/A
- we are going to add new campaign type and current DB schema does not fit it. In this PR change the schema to be agnostic to campaign type by keeping only common details in typed columns and all campaign specific details in `details` json column
- in order to have just one migration, also added fund token decimals that we will need for follow-up PRs (port rewards calculation from https://github.com/Hu-Fi/hufi/pull/372)
- also do renamed of `MARKET_MAKING` -> `VOLUME` campaign type.
> [!NOTE]
> Taking into account that we can sacrifice campaigns history in RecO DB for the release (all results live in blockchain), we implemented simplest possible migration and avoiding code parts for backward compatibility due to renaming of fields in manifest & intermediate results
As part of common …
=> [Oracles] feat: change campaign schema to support different types

recording-oracle/src/modules/campaigns/campaigns.repository.ts, recording-oracle/src/modules/campaigns/campaigns.service.spec.ts, recording-oracle/src/modules/campaigns/campaigns.service.ts, recording-oracle/src/modules/campaigns/fixtures/campaign.ts, recording-oracle/src/modules/campaigns/fixtures/manifest.ts
N/A
Refactored campaign service unit tests to abstract campaign types.
Also improved `findForProgressRecording` to query campaigns that ended, no matter when they started.
Just merge
No
=> [Recording Oracle] test: refactor campaign service unit tests to abstract campaign types
